name: Java Build and Run

on:
  push:
    branches:
      - main  # You can specify the branch you want to trigger this workflow on

jobs:
  build-and-run:
    runs-on: ubuntu-latest  # You can choose a different runner as needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This step checks out your repository code

    - name: Set up Java
      uses: actions/setup-java@v2  # This step sets up the Java environment
      with:
        java-version: '11'  # You can specify the Java version you want
        distribution: 'adopt'
        
    - name: where am i 2?
      run: cd ..
      
    - name: Compile Java
      run: javac HelloWorld.java  # Replace with your Java file name

    - name: Run Java
      run: java HelloWorld  # Replace with your Java class name

